### PR TITLE
Using addSpotify instead of addSpotifyQueue

### PR DESCRIPTION
**Pull request by truncj**
Pulled the update that fixes the new token requirements, but it looks like the old addSpotifyQueue function was uncommented. I recommented that and uncommented addSpotify, which works for me.

### CODE REVIEW

**Comment by htilly** [comment]
Thanks, yes the problem was solved in:
https://github.com/bencevans/node-sonos/issues/142

Merging!

**Comment by htilly** [comment]
btw, since addSpotify worked for you I guess you were using an US account for Spotify, right?

**Comment by truncj** [comment]
Yup, US region here. Does that mean we'll be able to use the one method for both regions?

**Comment by htilly** [comment]
Yea, so it seems. Lets see if it works of if issues is coming in =)

/Tilly

**Pull request merged**
