### PR TITLE
Add Dockerfile and fix Blacklist

### PR DESCRIPTION
**Pull request by jangrewe**
The blacklist was read asynchronously and didn't really stop any blacklisted user from sending commands - now it does.
The Dockerfile creates an Alpine based container that includes the config and blacklist at build time.

ToDo: environment variables to configure the Docker containers

### CODE REVIEW

**Comment by htilly** [comment]
Awesome!

**Comment by jangrewe** [comment]
Please be aware that there were a couple more changes besides the ones mentioned in the initial commit, especially how the blacklist is configured now and how configuration options can be set - this shouldn't break anything for existing users, but some people may be surprised that their blacklist.txt doesn't work anymore ;-)

**Comment by htilly** [comment]
Roger! 
Oho, if you do have some time to spend, please have a look at _gongPlay :-D

/Tilly

**Comment by jangrewe** [comment]
I will! We're "launching" it in our office today, so i'll probably hold off for a couple of days, but expect more PRs from me in the future ;-)

**Pull request merged**
